//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventCode { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string MapsLocation { get; set; }
        public string LocationsDescription { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string ReportedBy { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> NoOfRescued { get; set; }
        public Nullable<int> RescuedAges { get; set; }
        public string RescuedDesc { get; set; }
        public Nullable<int> NoOfFatalities { get; set; }
        public Nullable<int> NoOfSurvivors { get; set; }
        public int PersonInCharge { get; set; }
    }
}
