//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_EquipmentType
    {
        public int EventEventCode { get; set; }
        public int EquipmentTypeTypeCode { get; set; }
        public string Description { get; set; }
    }
}
