//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Photo { get; set; }
        public string PhoneNo { get; set; }
        public string Mail { get; set; }
        public string MirsNo { get; set; }
        public int CityCityCode { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactRelation { get; set; }
        public string ShirtSize { get; set; }
        public string PantsSize { get; set; }
        public string ShoesSize { get; set; }
        public Nullable<System.DateTime> MedicalTestDate { get; set; }
        //public DateTime MedicalTestDate { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
