//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDbContext : DbContext
    {
        public ProjectDbContext()
            : base("name=ProjectDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Event_EquipmentType> Event_EquipmentType { get; set; }
        public virtual DbSet<Event_Organization> Event_Organization { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<EventType_Event> EventType_Event { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Member_Event> Member_Event { get; set; }
        public virtual DbSet<Member_Team> Member_Team { get; set; }
        public virtual DbSet<Member_Team_qualification> Member_Team_qualification { get; set; }
        public virtual DbSet<Member_Team_Training> Member_Team_Training { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Particular_Event> Particular_Events { get; set; }
        public virtual DbSet<Qulification> Qulifications { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Training_Equipment> Training_Equipment { get; set; }
        public virtual DbSet<TrainingGoal> TrainingGoals { get; set; }
        public virtual DbSet<TrainingGoal_Training> TrainingGoal_Training { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
