//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Equipment
    {
        public int TrainingTrainingCode { get; set; }
        public int Equipment_EqCode { get; set; }
        public Nullable<int> RequieredQuantity { get; set; }
    }
}
